### ISSUE TITLE
Is there a way to query specific type of places in autocomplete?

### ISSUE THREAD

**Issue by mzmillat** [Bernardi23/search_map_place#13]
I would like to filter only specific type of places (i.e. gyms) with the autocomplete, is there a way to filter out other places in autocomplete?

**Comment by Bernardi23** [comment]
I'd have to look into the Maps API. But I think it's possible.

**Comment by Bernardi23** [comment]
I was doing some research on the API, and apparently the "Autocomplete API" (which is what was used to make this plugin), only support generic place types (geocode, address and establishment). The API that allows us to more precisely filter is the "Place Search API", and therefore cannot be used to create the autocompletion of the plugin. 

What I'll be implementing in the next version is the type of filtering that the "Autocompletion API" provides us, but like I said, it's not much precise.
