### ISSUE TITLE
is there a way to get the selected address out of the textbox

### ISSUE THREAD

**Issue by leadpresence** [Bernardi23/search_map_place#23]
The package works fine Kudos!!! however can one get the selected address?

**Comment by Bernardi23** [comment]
I think you're talking about the place description from the API. On the `onSelected` function, you can call `place.description`, which is the human readable string for the adress (the one used for the prediction). Something like this: 
```dart
SearchMapPlaceWidget(
  onSelected: (Place selectedPlace) {
    print(selectedPlace.description);
  }
)
```
