### ISSUE TITLE
Keyboard should minimize on select search place.

### ISSUE THREAD

**Issue by pavel-birdy** [Bernardi23/search_map_place#5]
```
  void _selectPlace(Place prediction) async {
.....
    FocusScope.of(context).unfocus(); // this code will remove the focus
  }
```
I think it would be a good idea and user experience to minimize the keyboard when the user selects a location. If we remove the focus from the `TextField`.

**Comment by Bernardi23** [comment]
That's a good idea. I'm no longer maintaining this plugin. But this is an easy fix so I guess I can do that.

**Comment by bhanuka96** [comment]
@Bernardi23 don't you maintain this plugin? can you give me the best plugin for that?
