### ISSUE TITLE
Lack for error messages 

### ISSUE THREAD

**Issue by chorauoc** [Bernardi23/search_map_place#7]
Hi,

I have notice that this plugin does not provide proper error msgs to identify the errors like this in your google Api calls, so i had to put debug msg to find the actual error msg. I hope you would look into this.

{
   "error_message" : "You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started",
   "results" : [],
   "status" : "REQUEST_DENIED"
}

Thanks
Chora

**Comment by Bernardi23** [comment]
I'll try to add this tomorrow
